In [30]:
import numpy as np
import pandas as pd
import random
from sklearn.metrics import confusion_matrix



In [36]:
def pegasos(X_df, y_df, lambda_reg, T):
    
    X = np.array(X_df)
    y = np.array(y_df)
    # Initialize the parameter
    n, d = X.shape
    w = np.zeros(d)
    a = 0
    t = 0
    eta = 0
    
    for epoch in range(1, T+1):
        list_of_tuples = [tuple(row) for row in X]
        shuffled_list = random.sample(list_of_tuples, n)
        X_shuffled= np.array([list(row) for row in shuffled_list])
        for i in range(n):
            t += 1
            eta = 1 / (lambda_reg * t)
            xt = X_shuffled[i, :]
            yt = y[i]

            if yt * (np.dot(xt,w)+a) < 1:
                step_w = lambda_reg*w - yt*xt
                step_a = -yt
            else:
                step_w = lambda_reg*w
                step_a = 0

            w = w - eta * step_w
            a = a - eta * step_a
       
    return w,a

def predict(w, X_test):
    
    predictions = np.dot(X_test, w)
    y_pred = np.sign(predictions)
    
    return y_pred

train_file_path = '/Users/wenqingz/Desktop/CodingAssignment5/coding5_train.csv'
test_file_path = '/Users/wenqingz/Desktop/CodingAssignment5/coding5_test.csv'

train_data = pd.read_csv(train_file_path)
test_data = pd.read_csv(test_file_path)

p = train_data.shape[1]-1 # The last column is "Y"

X = train_data.iloc[:,:p]
y = train_data.iloc[:,p]
X_test = test_data.iloc[:,:p]
y_test = test_data.iloc[:,p]

w,a = pegasos(X, y, lambda_reg = 1, T = 1000)

y_pred = predict(w, X_test)

cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

accuracy = np.trace(cm) / np.sum(cm)
precision = cm[1, 1] / np.sum(cm[:, 1])  # Precision for class 1
recall = cm[1, 1] / np.sum(cm[1, :])  # Recall for class 1

print("\nAccuracy:", accuracy)
print("Precision (Class 1):", precision)
print("Recall (Class 1):", recall)
    


Confusion Matrix:
[[  0   0   0]
 [300   0   0]
 [300   0   0]]

Accuracy: 0.0
Precision (Class 1): nan
Recall (Class 1): 0.0


/var/folders/km/8yg0mls91wbbtttgpt49t8_80000gn/T/ipykernel_16714/3239015983.py:64: RuntimeWarning: invalid value encountered in scalar divide
  precision = cm[1, 1] / np.sum(cm[:, 1])  # Precision for class 1


In [23]:
print(w.shape)
print(X_test.shape)

(256,)
(600, 256)


In [37]:
print(y_pred)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.